### ISSUE TITLE
Create the main BTree and BTreeNode (and supporting) classes

### ISSUE THREAD

**Issue by NoahSewBSU** [NoahSewBSU/CS321-002-f24-team-02#12]
Convert pseudocode into code for BTree.java class, Use the [pseudocode] - (https://github.com/BoiseState/CS321-resources/blob/master/notes/amit/btree-pseudocode.pdf) for 0-based arrays.

BTreeNode.java class (can be an inner class). What methods go into those classes?

Note, no support for deletion is required! You can simply leave that as an unsupported operation.

Use the provided TreeObject class.

Figure out how to do disk read and write -- this could be done in parallel with the development of the main pseudocode.

**Comment by Tdundy** [comment]
BTree constuctor and supporting classes have been started and pass Checkpoint 1 qualifications
