### ISSUE TITLE
Focus on running unit tests for BTree.

### ISSUE THREAD

**Issue by NoahSewBSU** [NoahSewBSU/CS321-002-f24-team-02#13]
We have provided a complete unit test for the main BTree class. This is in the following file (in your repo): test/java/cs321/btree/BTreeTest.java
Skeletons of other unit tests for other classes are also provided. In the interest of time, we do not necessarily expect you to work on those additional unit tests.

**Comment by Tdundy** [comment]
Finished code for BTree and it now passes all unit tests
